#! /usr/bin/env python

import Params
Params.parse_args()
Params.setup_logging()
Params.chdir()
listener = Params.get_listener()
Params.daemonize()

import Replicator
Replicator.run_event_loop(listener)
