.TH "HTTP REPLICATOR" 1 "August 18, 2004"
.SH NAME
http-replicator \- Replicating HTTP proxy server
.SH SYNOPSIS
.B http-replicator
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B http-replicator
command.
.PP
Replicator is a replicating HTTP proxy server. Files that are downloaded
through the proxy are transparently stored in a private cache, so an exact copy
of accessed remote files is created on the local machine. Please see the README
or the website for more information:
.PP
http://gertjan.freezope.org/replicator
.SH OPTIONS
This programs follow the usual GNU command line syntax, with long options
starting with two dashes (`-'). A summary of options is included below.
.TP
.BI "\-h, \-\-help "
Show summary of options.
.TP
.BI "\-p, \-\-port " port
The proxy port on which the server listens for http requests. Default is 8080.
.TP
.BI "\-i, \-\-ip " ip
An ip address from which access is allowed, optionally with wildcards ? and *
for single and multiple digits respectivily. Defaults to localhost and can be
used multiple times. 
.TP
.BI "\-d, \-\-dir " dir
The directory to store the cached files in. By default files are simply saved
in the current directory. 
.TP
.BI "\-a, \-\-alias " str
Colon separated list of mirrors, i.e. hosts serving identical content. Useful
for caching (debian) packages from different mirrors to the same directory,
like this: 'cache/dir:host1/somepath:host2/other/path'. Can be used multiple
times.
.TP
.BI "\-s, \-\-static "
Static mode: files are known to never change so files that are present are
served from cache directly without contacting the server.
.TP
.BI "\-f, \-\-flat "
Flat mode: all files are saved in a single directory.
.TP
.BI "\-l, \-\-local "
Serve files from a local directory if the proxy address is accessed directly.
.TP
.BI "\-e, \-\-external " ex
Forward requests to an external proxy server, specified as
.IR host:port " or " username:password@host:port
if the server requires authentication. 
.TP
.BI "\-q, \-\-quiet "
Decrease verbosity. Messages on stdout all have a certain level of importancy.
By repeatedly selecting this option the least important messages are skipped. 
.PP
Daemon options: 
.TP
.BI "\-\-daemon "
Switch to daemon mode and activate the following options:
.TP
.BI "\-\-log " log
Send output to a log file instead of stdout. 
.TP
.BI "\-\-pid " pid
Write the process id to a pid file instead of stdout. 
.TP
.BI "\-\-user " user
Change the process user id after opening the log and pid file. 
.PP
Debugging options: 
.TP
.BI "\-\-debug "
Set the lowest possible logging level (the quiet option is ignored) and activate the
following options: 
.TP
.BI "\-\-intolerant "
Crash on unhandled exceptions. 
.SH AUTHOR
Written by Gertjan van Zwieten <gertjanvanzwieten@fastmail.fm>.
