#! /bin/bash

TESTS=13
PORT=8090
PID="/tmp/replicator.$PORT"
PREFIX="/tmp/unittest$1"
URL_HTTP="www.w3.org:80/Protocols/HTTP/1.1/rfc2616.txt.gz"
URL_CHUNKED="jigsaw.w3.org:80/HTTP/ChunkedScript"
URL_FTP="ftp.debian.org:21/debian/doc/FAQ/debian-faq.en.pdf.gz"

if test -z "$1"; then
  while [ $((++i)) -le $TESTS ]; do
    $0 $i
    echo ========================================================================
  done
  exit 0
fi

function startserver
{
  rm -rf $PREFIX.*
  mkdir $PREFIX.cache
  if ! ./http-replicator -p $PORT -r $PREFIX.cache -v -v $@ -d $PREFIX.log > $PID; then
    cat $PID
    rm $PID
    exit 1
  fi
}

function stopserver
{
  kill -int `cat $PID`
  rm $PID
}

function exists
{
  if test -e $1; then
    echo OK;
  else
    echo ERROR;
  fi
}

function compare
{
  if test ! -e $1; then
    echo ERROR: 1st file missing
  elif test ! -e $2; then
    echo ERROR: 2nd file missing
  elif test `md5 -q $1` != `md5 -q $2`; then
    echo ERROR: files not equal
  else
    echo OK
  fi
}

function logged
{
  if grep -q "$1" $PREFIX.log; then
    echo OK;
  else
    echo ERROR;
  fi
}

case $1 in
  1)
    echo "TEST $1: DOWNLOADING NEW FILE"
    startserver
    curl -o $PREFIX.out1 http://$URL_HTTP -#
    curl -x localhost:$PORT -o $PREFIX.out2 http://$URL_HTTP -#
    sleep .5
    echo " * file cached and finalized ........................................... `exists $PREFIX.cache/$URL_HTTP`"
    echo " * separate download and served file are equal ......................... `compare $PREFIX.out1 $PREFIX.out2`"
    echo " * cached and served file are equal .................................... `compare $PREFIX.cache/$URL_HTTP $PREFIX.out2`"
    stopserver
    ;;
  2)
    echo "TEST $1: LEAVING PARTIAL FILE IN CACHE"
    startserver
    curl -x localhost:$PORT -o $PREFIX.out http://$URL_HTTP -# &
    sleep 1
    kill %
    echo
    sleep .5
    echo " * file cached, not finalized .......................................... `exists $PREFIX.cache/$URL_HTTP.incomplete`"
    stopserver
    ;;
  3)
    echo "TEST $1: SERVING FILE FROM CACHE"
    startserver
    curl -x localhost:$PORT -o $PREFIX.out1 http://$URL_HTTP -#
    curl -x localhost:$PORT -o $PREFIX.out2 http://$URL_HTTP -#
    sleep .5
    echo " * first file cached and finalized ..................................... `exists $PREFIX.cache/$URL_HTTP`"
    echo " * second file served from cache ....................................... `logged 'Complete file in cache'`"
    echo " * cached and first served file are equal .............................. `compare $PREFIX.cache/$URL_HTTP $PREFIX.out1`"
    echo " * cached and second served file are equal ............................. `compare $PREFIX.cache/$URL_HTTP $PREFIX.out2`"
    stopserver
    ;;
  4)
    echo "TEST $1: RESUMING PARTIAL FILE BY CLIENT"
    startserver
    curl -o $PREFIX.out http://$URL_HTTP -# &
    sleep 1
    kill %
    echo
    sleep .5
    curl -x localhost:$PORT -C - -o $PREFIX.out http://$URL_HTTP -#
    sleep .5
    echo " * received complete file .............................................. `logged 'Server sends HTTP/1.1 200 OK'`"
    echo " * served partial file ................................................. `logged 'Sending HTTP/1.1 206 Partial Content'`"
    echo " * cached and served file are equal .................................... `compare $PREFIX.cache/$URL_HTTP $PREFIX.out`"
    stopserver
    ;;
  5)
    echo "TEST $1: REDOWNLOADING CHANGED FILE"
    startserver
    mkdir -p $PREFIX.cache/$URL_HTTP
    rmdir $PREFIX.cache/$URL_HTTP
    touch -m -t 190112140000 $PREFIX.cache/$URL_HTTP
    curl -x localhost:$PORT -o $PREFIX.out http://$URL_HTTP -#
    sleep .5
    echo " * detected complete file in cache ..................................... `logged 'Complete file in cache'`"
    echo " * downloading new file ................................................ `logged 'Opening new file'`"
    echo " * cached and served file are equal .................................... `compare $PREFIX.cache/$URL_HTTP $PREFIX.out`"
    stopserver
    ;;
  6)
    echo "TEST $1: RESUMING PARTIAL UNCHANGED FILE IN CACHE"
    startserver
    curl -x localhost:$PORT -o $PREFIX.out http://$URL_HTTP -# &
    sleep 1
    kill %
    echo
    sleep .5
    curl -x localhost:$PORT -o $PREFIX.out http://$URL_HTTP -#
    sleep .5
    echo " * replicator asks for missing part..................................... `logged 'Partial file in cache'`"
    echo " * received partial file ............................................... `logged 'Server sends HTTP/1.1 206 Partial Content'`"
    echo " * cached and served file are equal .................................... `compare $PREFIX.cache/$URL_HTTP $PREFIX.out`"
    stopserver
    ;;
  7)
    echo "TEST $1: RESUMING PARTIAL CHANGED FILE IN CACHE"
    startserver
    mkdir -p $PREFIX.cache/$URL_HTTP
    rmdir $PREFIX.cache/$URL_HTTP
    ps aux > $PREFIX.cache/$URL_HTTP.incomplete
    curl -x localhost:$PORT -o $PREFIX.out http://$URL_HTTP -#
    sleep .5
    echo " * replicator asks for missing part..................................... `logged 'Partial file in cache'`"
    echo " * received complete file .............................................. `logged 'Server sends HTTP/1.1 200 OK'`"
    echo " * cached and served file are equal .................................... `compare $PREFIX.cache/$URL_HTTP $PREFIX.out`"
    stopserver
    ;;
  8)
    echo "TEST $1: JOINING DOWNLOADS"
    startserver
    echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%% FIRST DOWNLOAD %%%%%%%%%%%%%%%%%%%%%%%%%%%%"
    curl -x localhost:$PORT -o $PREFIX.out1 http://$URL_HTTP -s &
    sleep 1
    curl -x localhost:$PORT -o $PREFIX.out2 http://$URL_HTTP -#
    sleep .5
    echo " * downloads are joined ................................................ `logged 'Joined running download'`"
    echo " * cached and first served file are equal .............................. `compare $PREFIX.cache/$URL_HTTP $PREFIX.out1`"
    echo " * cached and second served file are equal ............................. `compare $PREFIX.cache/$URL_HTTP $PREFIX.out2`"
    stopserver
    ;;
  9)
    echo "TEST $1: DOWNLOADING NEW FILE, CHUNKED TRANSFER"
    startserver
    curl -o $PREFIX.out1 http://$URL_CHUNKED -#
    curl -x localhost:$PORT -o $PREFIX.out2 http://$URL_CHUNKED -#
    sleep .5
    echo " * separate download and served file are equal ......................... `compare $PREFIX.out1 $PREFIX.out2`"
    echo " * server sends chunked data ........................................... `logged 'Transfer-Encoding: chunked'`"
    echo " * processing chunked data ............................................. `logged 'Switching to ChunkedDataResponse'`"
    echo " * cached and served file are equal .................................... `compare $PREFIX.cache/$URL_CHUNKED $PREFIX.out2`"
    stopserver
    ;;
  10)
    echo "TEST $1: DOWNLOADING NEW FILE, FTP TRANSFER"
    startserver
    curl -o $PREFIX.out1 ftp://$URL_FTP -#
    curl -x localhost:$PORT -o $PREFIX.out2 ftp://$URL_FTP -#
    sleep .5
    echo " * separate download and served file are equal ......................... `compare $PREFIX.out1 $PREFIX.out2`"
    echo " * cached and served file are equal .................................... `compare $PREFIX.cache/$URL_FTP $PREFIX.out2`"
    stopserver
    ;;
  11)
    echo "TEST $1: SERVING FILE FROM CACHE, FTP TRANSFER"
    startserver
    curl -x localhost:$PORT -o $PREFIX.out1 ftp://$URL_FTP -#
    curl -x localhost:$PORT -o $PREFIX.out2 ftp://$URL_FTP -#
    sleep .5
    echo " * first file cached and finalized ..................................... `exists $PREFIX.cache/$URL_FTP`"
    echo " * second file served from cache ....................................... `logged 'Serving complete file from cache'`"
    echo " * cached and first served file are equal .............................. `compare $PREFIX.cache/$URL_FTP $PREFIX.out1`"
    echo " * cached and second served file are equal ............................. `compare $PREFIX.cache/$URL_FTP $PREFIX.out2`"
    stopserver
    ;;
  12)
    echo "TEST $1: RESUMING PARTIAL UNCHANGED FILE IN CACHE, FTP TRANSFER"
    startserver
    curl -x localhost:$PORT -o $PREFIX.out ftp://$URL_FTP -# &
    sleep 1
    kill %
    echo
    sleep .5
    curl -x localhost:$PORT -o $PREFIX.out ftp://$URL_FTP -#
    sleep .5
    echo " * replicator resumes file ............................................. `logged 'Resuming partial file in cache'`"
    echo " * cached and served file are equal .................................... `compare $PREFIX.cache/$URL_FTP $PREFIX.out`"
    stopserver
    ;;
  13)
    echo "TEST $1: RATE CONTROL"
    startserver --limit 10
    curl -x localhost:$PORT -o $PREFIX.out http://$URL_HTTP
    sleep .5
    echo " * download speed approximately equal to 10240 ......................... ^^^^^"
    echo " * cached and served file are equal .................................... `compare $PREFIX.cache/$URL_HTTP $PREFIX.out`"
    stopserver
esac
