#! /bin/bash

TESTS=8
URL="www.w3.org:80/Protocols/HTTP/1.1/rfc2616.txt.gz"
PORT="8090"
BASE="/tmp/unittest$1"
CACHE="$BASE.cache"
LOG="$BASE.log"
OUT="$BASE.out"

if [ -z "$1" ]; then
  while [ $((++i)) -le $TESTS ]; do
    $0 $i
    echo ========================================================================
  done
  exit 0
fi

function exists
{
  if test -e $1; then echo OK; else echo ERROR; fi
}

function compare
{
  if test ! -e $1; then
    echo ERROR: 1st file missing
  elif test ! -e $2; then
    echo ERROR: 2nd file missing
  elif test `md5 -q $1` != `md5 -q $2`; then
    echo ERROR: files not equal
  else
    echo OK
  fi
}

function logged
{
  if grep -q "$1" $LOG; then echo OK; else echo ERROR; fi
}

echo -n "UNITTEST $1: "
set -m
rm -rf $BASE.*
mkdir $CACHE
./http-replicator -p $PORT -r $CACHE -v -v > $LOG &
sleep .5
case $1 in
  1)
    echo "DOWNLOADING NEW FILE"
    curl -x localhost:$PORT -o $OUT http://$URL -#
    sleep .5
    echo " * file cached and finalized ........................................... `exists $CACHE/$URL`"
    echo " * cached and served file are equal .................................... `compare $CACHE/$URL $OUT`"
    ;;
  2)
    echo "LEAVING PARTIAL FILE IN CACHE"
    curl -x localhost:$PORT -o $OUT http://$URL -# &
    sleep 1
    kill -int %+
    echo
    sleep .5
    echo " * file cached, not finalized .......................................... `exists $CACHE/$URL.incomplete`"
    ;;
  3)
    echo "SERVING FILE FROM CACHE"
    curl -x localhost:$PORT -o ${OUT}1 http://$URL -#
    curl -x localhost:$PORT -o ${OUT}2 http://$URL -#
    sleep .5
    echo " * first file cached and finalized ..................................... `exists $CACHE/$URL`"
    echo " * second file served from cache ....................................... `logged 'Complete file in cache'`"
    echo " * cached and first served file are equal .............................. `compare $CACHE/$URL ${OUT}1`"
    echo " * cached and second served file are equal ............................. `compare $CACHE/$URL ${OUT}2`"
    ;;
  4)
    echo "RESUMING PARTIAL FILE BY CLIENT"
    curl -o $OUT http://$URL -# &
    sleep 1
    kill -int %+
    echo
    curl -x localhost:$PORT -C - -o $OUT http://$URL -#
    sleep .5
    echo " * received complete file .............................................. `logged 'Server sends HTTP/1.1 200 OK'`"
    echo " * served partial file ................................................. `logged 'Sending HTTP/1.1 206 Partial Content'`"
    echo " * cached and served file are equal .................................... `compare $CACHE/$URL $OUT`"
    ;;
  5)
    echo "REDOWNLOADING CHANGED FILE"
    mkdir -p $CACHE/$URL
    rmdir $CACHE/$URL
    touch -m -t 190112140000 $CACHE/$URL
    curl -x localhost:$PORT -o $OUT http://$URL -#
    sleep .5
    echo " * detected complete file in cache ..................................... `logged 'Complete file in cache'`"
    echo " * downloading new file ................................................ `logged 'Opening new file'`"
    echo " * cached and served file are equal .................................... `compare $CACHE/$URL $OUT`"
    ;;
  6)
    echo "RESUMING PARTIAL UNCHANGED FILE IN CACHE"
    curl -x localhost:$PORT -o $OUT http://$URL -# &
    sleep 1
    kill -int %+
    echo
    sleep .5
    curl -x localhost:$PORT -o $OUT http://$URL -#
    sleep .5
    echo " * replicator asks for missing part..................................... `logged 'Partial file in cache'`"
    echo " * received partial file ............................................... `logged 'Server sends HTTP/1.1 206 Partial Content'`"
    echo " * cached and served file are equal .................................... `compare $CACHE/$URL $OUT`"
    ;;
  7)
    echo "RESUMING PARTIAL CHANGED FILE IN CACHE"
    mkdir -p $CACHE/$URL
    rmdir $CACHE/$URL
    ps aux > $CACHE/$URL.incomplete
    curl -x localhost:$PORT -o $OUT http://$URL -#
    sleep .5
    echo " * replicator asks for missing part..................................... `logged 'Partial file in cache'`"
    echo " * received complete file .............................................. `logged 'Server sends HTTP/1.1 200 OK'`"
    echo " * cached and served file are equal .................................... `compare $CACHE/$URL $OUT`"
    ;;
  8)
    echo "JOINING DOWNLOADS"
    echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%% FIRST DOWNLOAD %%%%%%%%%%%%%%%%%%%%%%%%%%%%"
    curl -x localhost:$PORT -o ${OUT}1 http://$URL -s &
    sleep 1
    curl -x localhost:$PORT -o ${OUT}2 http://$URL -#
    sleep .5
    echo " * downloads are joined ................................................ `logged 'Joined running download'`"
    echo " * cached and first served file are equal .............................. `compare $CACHE/$URL ${OUT}1`"
    echo " * cached and second served file are equal ............................. `compare $CACHE/$URL ${OUT}2`"
    ;;
  9)
    echo "CHUNKED DATA TRANSFER"
    curl -x localhost:$PORT -o $OUT http://jigsaw.w3.org/HTTP/ChunkedScript -#
    sleep .5
    echo " * server sends chunked data ........................................... `logged 'Transfer-Encoding: chunked'`"
    echo " * processing chunked data ............................................. `logged 'Switching to ChunkedDataResponse'`"
    echo " * cached and served file are equal .................................... `compare $CACHE/jigsaw.w3.org:80/HTTP/ChunkedScript $OUT`"
    ;;
  *)
    echo "Not implemented"
    ;;
esac
kill -int %-
