#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/http-replicator
NAME=http-replicator
DESC="HTTP Proxy"

if [ -x $DAEMON ] && [ -f /etc/default/$NAME ] ; then
	source /etc/default/$NAME
else
	exit 0
fi

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --pidfile /var/run/$NAME.pid --name $NAME \
	  --startas $DAEMON -- $DAEMON_OPTS --pid /var/run/$NAME.pid --daemon
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --pidfile /var/run/$NAME.pid --name $NAME \
	  --signal 2
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --pidfile /var/run/$NAME.pid --name $NAME \
	  --signal 2 --oknodo --quiet
	sleep 1
	start-stop-daemon --start --pidfile /var/run/$NAME.pid --name $NAME \
	  --startas $DAEMON -- $DAEMON_OPTS --pid /var/run/$NAME.pid --daemon
	echo "$NAME."
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
